```properties
sonar.projectKey=PallavSharma-oss_Restaurant-Food-Ordering-Management-System--React-MERN-FullStack-main
sonar.organization=pallav-sharma-123

sonar.host.url=https://sonarcloud.io
sonar.sources=food-ordering-backend,food-ordering-frontend
sonar.sourceEncoding=UTF-8

sonar.exclusions=**/node_modules/**,**/dist/**,**/.terraform/**,**/coverage/**,**/build/**
```
