name: Restaurant CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Node.js
        run: |
          node -v
          npm -v

      ###############################
      # Frontend
      ###############################

      - name: Install Frontend Dependencies
        working-directory: food-ordering-frontend
        run: npm install

      - name: Build Frontend
        working-directory: food-ordering-frontend
        run: npm run build

      ###############################
      # Backend
      ###############################

      - name: Install Backend Dependencies
        working-directory: food-ordering-backend
        run: npm install

      - name: Build Backend
        working-directory: food-ordering-backend
        run: npm run build