name: Restaurant CI/CD Pipeline

on:
  push:
    branches:
      - main

  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verify Node.js
        run: |
          node -v
          npm -v

      - name: Install Frontend Dependencies
        working-directory: food-ordering-frontend
        run: npm install

      - name: Build Frontend
        working-directory: food-ordering-frontend
        run: npm run build

      - name: Install Backend Dependencies
        working-directory: food-ordering-backend
        run: npm install

      - name: Build Backend
        working-directory: food-ordering-backend
        run: npm run build

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Frontend Docker Image
        run: docker build -t restaurant-frontend:latest ./food-ordering-frontend

      - name: Build Backend Docker Image
        run: docker build -t restaurant-backend:latest ./food-ordering-backend

      - name: Verify Docker Images
        run: docker images

      ####################################
      # Configure AWS Credentials (OIDC)
      ####################################

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::857235392758:role/github-actions-ecs-role
          aws-region: ap-south-1

      - name: Verify AWS Identity
        run: aws sts get-caller-identity
      ####################################
      # Login to Amazon ECR
      ####################################

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

              ####################################
      # Tag Docker Images
      ####################################

      - name: Tag Frontend Image
        run: |
          docker tag restaurant-frontend:latest \
          857235392758.dkr.ecr.ap-south-1.amazonaws.com/restaurant-frontend:latest

      - name: Tag Backend Image
        run: |
          docker tag restaurant-backend:latest \
          857235392758.dkr.ecr.ap-south-1.amazonaws.com/restaurant-backend:latest

      ####################################
      # Push Images to Amazon ECR
      ####################################

      - name: Push Frontend Image
        run: |
          docker push 857235392758.dkr.ecr.ap-south-1.amazonaws.com/restaurant-frontend:latest

      - name: Push Backend Image
        run: |
          docker push 857235392758.dkr.ecr.ap-south-1.amazonaws.com/restaurant-backend:latest